package com.guosai.entity;
// Generated 2018-10-24 20:18:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCarorder generated by hbm2java
 */
@Entity
@Table(name = "t_carorder", catalog = "db_xiaomi")
public class Carorder implements java.io.Serializable {

	private Integer id;
	private String goodsName;
	private Double price;
	private Integer num;
	private Double count;

	public Carorder() {
	}

	public Carorder(String goodsName, Double price, Integer num, Double count) {
		this.goodsName = goodsName;
		this.price = price;
		this.num = num;
		this.count = count;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "goodsName", length = 30)
	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	@Column(name = "price", precision = 10)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "num")
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Column(name = "count", precision = 22, scale = 0)
	public Double getCount() {
		return this.count;
	}

	public void setCount(Double count) {
		this.count = count;
	}

}
