package com.guosai.entity;
// Generated 2018-10-24 20:18:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TCart generated by hbm2java
 */
@Entity
@Table(name = "t_cart", catalog = "db_xiaomi")
public class Cart implements java.io.Serializable {

	private Integer id;
	private Goods goods;
	private User user;
	private Double num;

	public Cart() {
	}

	public Cart(Goods goods, User user, Double num) {
		this.goods = goods;
		this.user = user;
		this.num = num;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goodId")
	public Goods getTGoods() {
		return this.goods;
	}

	public void setTGoods(Goods goods) {
		this.goods = goods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid")
	public User getTUser() {
		return this.user;
	}

	public void setTUser(User user) {
		this.user = user;
	}

	@Column(name = "num", precision = 22, scale = 0)
	public Double getNum() {
		return this.num;
	}

	public void setNum(Double num) {
		this.num = num;
	}

}
