package com.guosai.entity;
// Generated 2018-10-24 20:18:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TOrderdetail generated by hbm2java
 */
@Entity
@Table(name = "t_orderdetail", catalog = "db_xiaomi")
public class Orderdetail implements java.io.Serializable {

	private Integer id;
	private Goods goods;
	private Order order;
	private Double num;

	public Orderdetail() {
	}

	public Orderdetail(Goods goods, Order order, Double num) {
		this.goods = goods;
		this.order = order;
		this.num = num;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goodsId")
	public Goods getTGoods() {
		return this.goods;
	}

	public void setTGoods(Goods goods) {
		this.goods = goods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderId")
	public Order getTOrder() {
		return this.order;
	}

	public void setTOrder(Order order) {
		this.order = order;
	}

	@Column(name = "num", precision = 2, scale = 0)
	public Double getNum() {
		return this.num;
	}

	public void setNum(Double num) {
		this.num = num;
	}

}
